package.json: fix `pnpm test` for nodejs 20.9.0
This fixes:

```

> NODE_OPTIONS='--loader=tsx --no-warnings' ./node_modules/.bin/ava && ./node_modules/.bin/tsc --target esnext --moduleResolution node --noEmit tests/*.ts && ./node_modules/.bin/eslint .

node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
Error: tsx must be loaded with --import instead of --loader
The --loader flag was deprecated in Node v20.6.0
    at X (file:///home/at/code/websites/cards/node_modules/.pnpm/tsx@3.14.0/node_modules/tsx/dist/esm/index.mjs:1:1920)
    at Hooks.addCustomLoader (node:internal/modules/esm/hooks:178:24)
    at Hooks.register (node:internal/modules/esm/hooks:144:16)
    at async initializeHooks (node:internal/modules/esm/utils:184:5)
    at async customizedModuleWorker (node:internal/modules/esm/worker:86:24)

Node.js v20.9.0
 ELIFECYCLE  Test failed. See above for more details.
```

Needed to change "module" -> "commonjs" as mentioned in
https://github.com/avajs/ava/discussions/3213#discussioncomment-6199261