cookied: fix complaint from tsc
packages/demo test$ ./node_modules/.bin/tsc -p tsconfig.json --noEmit && ./node_modules/.bin/eslint .
│ ../cookied/lib/kit/session.ts(5,1): error TS1371: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.
│ ../cookied/lib/kit/session.ts(5,10): error TS1444: 'Config' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.