Add missing @sveltejs/vite-plugin-svelte
This fixes

```
error when starting dev server:
Error: Could not resolve peer dependency "@sveltejs/vite-plugin-svelte" relative to your project — please install it and try again.
    at resolve_peer_dependency (cookied/node_modules/.pnpm/@sveltejs+kit@2.3.2_@sveltejs+vite-plugin-svelte@3.0.1_svelte@4.2.8_vite@5.0.11/node_modules/@sveltejs/kit/src/exports/vite/index.js:136:9)
    at sveltekit (cookied/node_modules/.pnpm/@sveltejs+kit@2.3.2_@sveltejs+vite-plugin-svelte@3.0.1_svelte@4.2.8_vite@5.0.11/node_modules/@sveltejs/kit/src/exports/vite/index.js:173:27)
    at async Promise.all (index 0)
    at async asyncFlatten (cookied/node_modules/.pnpm/vite@5.0.11_@types+node@20.11.0/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:12894:16)
    at async resolveConfig (cookied/node_modules/.pnpm/vite@5.0.11_@types+node@20.11.0/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:67863:29)
    at async _createServer (cookied/node_modules/.pnpm/vite@5.0.11_@types+node@20.11.0/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:60327:20)
    at async CAC.<anonymous> (cookied/node_modules/.pnpm/vite@5.0.11_@types+node@20.11.0/node_modules/vite/dist/node/cli.js:764:24)
 ELIFECYCLE  Command failed with exit code 1.
```